export * from './elemento.controller';
export * from './entrada.controller';
export * from './funcionario.controller';
export * from './ping.controller';
export * from './prestamo.controller';
export * from './prestante.controller';
export * from './salida.controller';
export * from './grado.controller';
export * from './dependencia.controller';
